# Generated by Django 4.2.7 on 2023-11-19 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gov_id', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('position', models.CharField(choices=[('Driver', 'Driver'), ('Administration Staff', 'Administration Staff'), ('Fueling Person', 'Fueling Person'), ('Maintenance Person', 'Maintenance Person')], max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuctionVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='auction_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VEHICLE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MAKE', models.CharField(max_length=50)),
                ('MODEL', models.CharField(max_length=50)),
                ('YEAR', models.IntegerField()),
                ('LIC_PLATE', models.CharField(max_length=20, unique=True)),
                ('TYPE', models.CharField(max_length=50)),
                ('MILEAGE', models.FloatField()),
                ('USED_TIME', models.DurationField()),
                ('SITTING_CAP', models.IntegerField()),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DRIVER_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('ROUTE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('START_TIME', models.DateTimeField()),
                ('FINISH_TIME', models.DateTimeField()),
                ('START_LOC', models.CharField(max_length=100)),
                ('FINISH_LOC', models.CharField(max_length=100)),
                ('DISTANCE', models.FloatField()),
                ('PURPOSE', models.TextField()),
                ('STATUS', models.CharField(max_length=50)),
                ('DRIVER_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('VEHICLE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(max_length=50)),
                ('DRIVER_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('VEHICLE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('mileage', models.FloatField()),
                ('plate_number', models.CharField(max_length=20)),
                ('job_description', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Non-Active', 'Non-Active')], max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('replaced_part_image', models.ImageField(upload_to='replaced_parts/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelRequest',
            fields=[
                ('REG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('STATUS', models.CharField(max_length=50)),
                ('DRIVER_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('VEHICLE_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('amount_of_fuel', models.FloatField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_station_name', models.CharField(max_length=100)),
                ('fueling_person_name', models.CharField(max_length=100)),
                ('before_image', models.ImageField(upload_to='fueling_records/before/')),
                ('after_image', models.ImageField(upload_to='fueling_records/after/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DRIVER_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('VEHICLE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.vehicle')),
            ],
        ),
    ]
