# Generated by Django 4.2.7 on 2023-11-22 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_remove_vehicle_driver_id_alter_auctionvehicle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequest',
            name='DRIVER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelrequest',
            name='VEHICLE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='maintrequest',
            name='DRIVER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
